import type {
  Crop,
  Affliction,
  KnowledgeSource,
  AlgerianWilaya,
} from "./types";

export const KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  {
    id: "itgc",
    acronym: "ITGC",
    fullName: {
      en: "Technical Institute of Field Crops",
      ar: "المعهد التقني للمحاصيل الحقلية",
      fr: "Institut Technique des Grandes Cultures",
    },
    institutionType: "technical_institute",
    url: "http://www.itgc.dz",
    provenance: "ITGC Cereal & Legume Agrotechnical Fiches (Algiers/Sétif/Sidi Bel Abbès)",
  },
  {
    id: "inraa",
    acronym: "INRAA",
    fullName: {
      en: "National Agricultural Research Institute of Algeria",
      ar: "المعهد الوطني للأبحاث الزراعية بالجزائر",
      fr: "Institut National de la Recherche Agronomique d'Algérie",
    },
    institutionType: "research_institute",
    url: "http://www.inraa.dz",
    provenance: "INRAA National Agronomic Research Bulletin & Varietal Guides",
  },
  {
    id: "itdas",
    acronym: "ITDAS",
    fullName: {
      en: "Technical Institute for the Development of Saharan Agronomy",
      ar: "المعهد التقني لتطوير الزراعة الصحراوية",
      fr: "Institut Technique de Développement de l'Agronomie Saharienne",
    },
    institutionType: "technical_institute",
    url: "http://www.itdas.dz",
    provenance: "ITDAS Phoenix Dactylifera & Saharan Oasis Technical Guide (Biskra)",
  },
  {
    id: "cnma",
    acronym: "CNMA",
    fullName: {
      en: "National Agricultural Mutual Fund",
      ar: "الصندوق الوطني للتعاون الفلاحي",
      fr: "Caisse Nationale de Mutualité Agricole",
    },
    institutionType: "insurance",
    url: "http://www.cnma.dz",
    provenance: "CNMA Agricultural Climate Risk & Agro-Sanitary Guides",
  },
  {
    id: "madr",
    acronym: "MADR",
    fullName: {
      en: "Ministry of Agriculture and Rural Development",
      ar: "وزارة الفلاحة والتنمية الريفية",
      fr: "Ministère de l'Agriculture et du Développement Rural",
    },
    institutionType: "ministry",
    url: "http://madr.gov.dz",
    provenance: "MADR Algerian Agricultural Statistics & National Crop Calendars",
  },
];

export const ALGERIAN_WILAYAS: AlgerianWilaya[] = [
  {
    code: "07",
    name: { en: "Biskra", ar: "بسكرة", fr: "Biskra" },
    zone: "saharan_oases",
    primaryCrops: ["date-palm", "tomato"],
  },
  {
    code: "19",
    name: { en: "Sétif", ar: "سطيف", fr: "Sétif" },
    zone: "high_plateaus",
    primaryCrops: ["durum-wheat", "barley", "potato"],
  },
  {
    code: "29",
    name: { en: "Mascara", ar: "معسكر", fr: "Mascara" },
    zone: "semi_arid_steppes",
    primaryCrops: ["olive", "durum-wheat", "citrus"],
  },
  {
    code: "27",
    name: { en: "Mostaganem", ar: "مستغانم", fr: "Mostaganem" },
    zone: "coastal_tell",
    primaryCrops: ["potato", "citrus", "tomato"],
  },
  {
    code: "09",
    name: { en: "Blida", ar: "البليدة", fr: "Blida" },
    zone: "coastal_tell",
    primaryCrops: ["citrus", "olive"],
  },
  {
    code: "24",
    name: { en: "Guelma", ar: "قالمة", fr: "Guelma" },
    zone: "coastal_tell",
    primaryCrops: ["durum-wheat", "tomato"],
  },
  {
    code: "14",
    name: { en: "Tiaret", ar: "تيارت", fr: "Tiaret" },
    zone: "high_plateaus",
    primaryCrops: ["barley", "durum-wheat"],
  },
  {
    code: "02",
    name: { en: "Chlef", ar: "الشلف", fr: "Chlef" },
    zone: "semi_arid_steppes",
    primaryCrops: ["citrus", "olive"],
  },
  {
    code: "05",
    name: { en: "Batna", ar: "باتنة", fr: "Batna" },
    zone: "high_plateaus",
    primaryCrops: ["durum-wheat", "barley", "apple"],
  },
  {
    code: "39",
    name: { en: "El Oued", ar: "الوادي", fr: "El Oued" },
    zone: "saharan_oases",
    primaryCrops: ["potato", "date-palm"],
  },
  {
    code: "16",
    name: { en: "Algiers", ar: "الجزائر", fr: "Alger" },
    zone: "coastal_tell",
    primaryCrops: ["citrus", "vegetable"],
  },
  {
    code: "31",
    name: { en: "Oran", ar: "وهران", fr: "Oran" },
    zone: "coastal_tell",
    primaryCrops: ["olive", "durum-wheat"],
  },
];

export const AFFLICTIONS: Affliction[] = [
  {
    id: "septoria-tritici",
    type: "disease",
    scientificName: "Zymoseptoria tritici",
    name: {
      en: "Septoria Leaf Blotch",
      ar: "تبقع الأوراق السبتوري",
      fr: "Septoriose du blé",
    },
    severity: "high",
    symptoms: {
      en: "Necrotic irregular brown lesions on leaves containing small black pycnidia fruiting bodies.",
      ar: "بقع بنية نخرية غير منتظمة على الأوراق تحتوي على نقاط سوداء دقيقة.",
      fr: "Lésions foliaires nécrotiques brunâtres avec présence de petites pycnides noires.",
    },
    treatment: {
      en: "Preventive triazole/strobilurin fungicides at stem elongation, crop rotation, and resistant varieties (ITGC).",
      ar: "المعالجة الوقائية بمبيدات التريازول عند تطاول الساق، الدورة الزراعية، واستخدام أصناف مقاومة معتمدة من ITGC.",
      fr: "Fongicide préventif (triazoles/strobilurines) à la montaison, rotation culturale et variétés résistantes ITGC.",
    },
    affectedCropIds: ["durum-wheat", "barley"],
  },
  {
    id: "yellow-rust",
    type: "disease",
    scientificName: "Puccinia striiformis",
    name: {
      en: "Stripe / Yellow Rust",
      ar: "الصدأ الأصفر المخطط",
      fr: "Rouille jaune",
    },
    severity: "critical",
    symptoms: {
      en: "Parallel stripes of bright yellow powdery pustules along leaf veins during cool spring weather.",
      ar: "خطوط متوازية من البثور الصفراء الزاهية على طول عروق الورقة خلال طقس الربيع البارد والرطب.",
      fr: "Stries parallèles de pustules jaune vif le long des nervures foliaires par temps frais et humide.",
    },
    treatment: {
      en: "Immediate foliar systemic fungicide spray upon first pustule detection; prioritize certified resistant seeds.",
      ar: "الرش الفوري بمبيد جهازي عند ظهور أولى البثور الصفراء، واعتماد البذور المعتمدة المقاومة.",
      fr: "Application immédiate d'un fongicide systémique dès la détection; choix variétal résistant.",
    },
    affectedCropIds: ["durum-wheat", "barley"],
  },
  {
    id: "olive-fruit-fly",
    type: "pest",
    scientificName: "Bactrocera oleae",
    name: {
      en: "Olive Fruit Fly",
      ar: "ذبابة ثمار الزيتون",
      fr: "Mouche de l'olive",
    },
    severity: "high",
    symptoms: {
      en: "Triangular puncture mark on olive skin; internal larvae tunneling leading to fruit drop and high acidity.",
      ar: "وخزات مثلثية على قشرة حبة الزيتون مع حفر اليرقات داخل اللب مما يسبب تساقط الثمار وارتفاع الحموضة.",
      fr: "Piqures triangulaires sur fruits; galeries larvaires provoquant chute prématurée et acidité.",
    },
    treatment: {
      en: "McPhail pheromone trapping, chromatic sticky traps, spinosad/kaolin clay barrier sprays in early summer.",
      ar: "المصائد الفرمونية واللاصقة الصفراء، ورش طين الكاولين أو المبيدات الحيوية (سبينوزاد) بداية الصيف.",
      fr: "Piégeage de masse (phéromones/McPhail), barrière à l'argile kaolin et traitements bio (spinosad).",
    },
    affectedCropIds: ["olive"],
  },
  {
    id: "red-palm-weevil",
    type: "pest",
    scientificName: "Rhynchophorus ferrugineus",
    name: {
      en: "Red Palm Weevil",
      ar: "سوسة النخيل الحمراء",
      fr: "Charançon rouge du palmier",
    },
    severity: "critical",
    symptoms: {
      en: "Internal trunk burrowing, gnawing sounds, oozing brown viscous liquid, collapsing central fronds/crown.",
      ar: "نخر الجذع من الداخل، إفرازات بنية لزجة ذات رائحة كريهة، وجفاف وتهدل السعف القمي.",
      fr: "Destruction interne du stipe, exsudat brun visqueux, affaissement de la couronne centrale.",
    },
    treatment: {
      en: "Strict quarantine, acoustic detection, stem injection with systemic insecticides, pruning hygiene.",
      ar: "الحجر الزراعي الصارم، الكشف الصوتي، الحقن الجذعي بالمبيدات الجهازية، وتطهير أماكن التقليم.",
      fr: "Quarantaine stricte, détection acoustique, injection systémique et traitement préventif des coupes.",
    },
    affectedCropIds: ["date-palm"],
  },
  {
    id: "late-blight",
    type: "disease",
    scientificName: "Phytophthora infestans",
    name: {
      en: "Late Blight",
      ar: "اللفحة المتأخرة (الميلديو)",
      fr: "Mildiou de la pomme de terre",
    },
    severity: "critical",
    symptoms: {
      en: "Water-soaked dark lesions on leaf tips with white fuzzy mildew underneath in high humidity; tuber rot.",
      ar: "بقع زيتية داكنة على حواف الأوراق مع زغب أبيض قطني أسفل الورقة في الرطوبة، وتعفن الدرنات.",
      fr: "Taches huileuses brunes aux extrémités des feuilles avec duvet blanc en dessous; pourriture des tubercules.",
    },
    treatment: {
      en: "Copper fungicides preventive spray, destruction of infected haulms, avoidance of overhead irrigation.",
      ar: "المعالجة الوقائية بالنحاس، تجنب الري بالرش خلال الفترات الرطبة، وإتلاف الأعراش المصابة فوراً.",
      fr: "Traitements cupriques préventifs, destruction des fanes atteintes, gestion stricte de l'irrigation.",
    },
    affectedCropIds: ["potato", "tomato"],
  },
  {
    id: "tuta-absoluta",
    type: "pest",
    scientificName: "Tuta absoluta",
    name: {
      en: "Tomato Leafminer",
      ar: "حفارة أوراق الطماطم (توتا أبسولوتـا)",
      fr: "Mineuse de la tomate",
    },
    severity: "high",
    symptoms: {
      en: "Transparent silvery galleries in leaves, punctured green and ripe fruits with entry holes and frass.",
      ar: "أنفاق شفافة فضية داخل نصل الورقة، وثقوب ونخر في الثمار مع فضلات سوداء حول عنق الثمرة.",
      fr: "Mines foliaires transparentes, galeries et déjections dans les fruits verts et mûrs.",
    },
    treatment: {
      en: "Insect-proof netting in greenhouses, pheromone delta traps, biological control using Nesidiocoris tenuis.",
      ar: "الشباك المضادة للحشرات في البيوت البلاستيكية، المصائد الفرمونية المائية، والمكافحة الحيوية بحشرة النسيديوكوريس.",
      fr: "Filets insect-proof, piégeage phéromone de masse, lâchers d'auxiliaires (Nesidiocoris tenuis).",
    },
    affectedCropIds: ["tomato", "potato"],
  },
];

export const CROPS: Crop[] = [
  {
    id: "durum-wheat",
    slug: "durum-wheat",
    name: {
      en: "Durum Wheat",
      ar: "القمح الصلب",
      fr: "Blé Dur",
    },
    scientificName: "Triticum durum Desf.",
    family: "Poaceae",
    category: "cereal",
    description: {
      en: "Strategic cereal staple in Algeria, predominantly cultivated on High Plateaus and Tellian plains.",
      ar: "محصول استراتيجي رئيسي في الجزائر يتركز في الهضاب العليا والسهول التلية لإنتاج السميد والمعجنات.",
      fr: "Céréale stratégique majeure en Algérie, principalement cultivée dans les Hautes Plaines et les plaines telliennes.",
    },
    varieties: [
      {
        id: "simeto",
        name: "Simeto",
        code: "ITGC-SIM",
        recommendedZones: ["high_plateaus", "coastal_tell"],
        cycleDays: 160,
        maturity: "medium",
        description: {
          en: "High yielding, good industrial semolina quality, widely grown in Constantine and Sétif.",
          ar: "إنتاجية عالية وجودة سميد صناعية ممتازة، واسع الانتشار في سطيف وقسنطينة.",
          fr: "Très bon rendement, excellente qualité semoulière, très répandue à Sétif et Constantine.",
        },
      },
      {
        id: "vitron",
        name: "Vitron",
        code: "ITGC-VIT",
        recommendedZones: ["high_plateaus", "semi_arid_steppes"],
        cycleDays: 150,
        maturity: "early",
        description: {
          en: "Early variety, drought-tolerant, adapted to semi-arid cereal zones.",
          ar: "صنف مبكر متحمل للجفاف، مناسب للمناطق شبه الجافة في تيارت وسيدي بلعباس.",
          fr: "Variété précoce, tolérante au déficit hydrique, adaptée aux zones semi-arides.",
        },
      },
      {
        id: "waha",
        name: "Waha (HD 1220)",
        code: "ITGC-WAH",
        recommendedZones: ["high_plateaus"],
        cycleDays: 155,
        maturity: "medium",
        description: {
          en: "Historic certified Algerian variety known for cold and frost resilience.",
          ar: "صنف جزائري أصيل معتمد مقاوم للصقيع الربيعي وبرودة الهضاب العليا.",
          fr: "Variété historique certifiée réputée pour sa résistance au gel printanier.",
        },
      },
    ],
    calendar: [
      {
        phase: "sowing",
        name: { en: "Sowing Window", ar: "مرحلة البذر", fr: "Semis" },
        startMonth: 10,
        endMonth: 12,
        notes: {
          en: "Optimal sowing density 120-150 kg/ha depending on rainfall zone.",
          ar: "الكثافة المثالية 120-150 كغ/هكتار حسب معدل التساقط بالمنطقة.",
          fr: "Densité recommandée 120-150 kg/ha selon la zone pluviométrique.",
        },
      },
      {
        phase: "vegetative",
        name: { en: "Tillering & Stem Extension", ar: "التفريغ وتطاول الساق", fr: "Tallage & Montaison" },
        startMonth: 1,
        endMonth: 3,
      },
      {
        phase: "flowering",
        name: { en: "Heading & Flowering", ar: "طرد السنابل والإزهار", fr: "Épiaison & Floraison" },
        startMonth: 4,
        endMonth: 4,
      },
      {
        phase: "maturation",
        name: { en: "Grain Filling", ar: "امتلاء الحبوب والنضج", fr: "Remplissage du grain" },
        startMonth: 5,
        endMonth: 5,
      },
      {
        phase: "harvesting",
        name: { en: "Harvest Campaign", ar: "حملة الحصاد والدرس", fr: "Moisson-Battage" },
        startMonth: 6,
        endMonth: 7,
      },
    ],
    primaryWilayas: ["19", "24", "14", "05", "29"],
    requirements: {
      optimalTempMin: 12,
      optimalTempMax: 26,
      waterNeedsMm: 450,
      soilTypes: {
        en: "Deep clay-loam, well-drained with balanced organic matter.",
        ar: "تربة طينية طميية عميقة جيدة الصرف غنية بالمادة العضوية.",
        fr: "Sols argilo-limoneux profonds, bien drainés et fertiles.",
      },
      droughtTolerance: "moderate",
      salinityTolerance: "moderate",
    },
    afflictionIds: ["septoria-tritici", "yellow-rust"],
    sources: ["itgc", "inraa", "madr"],
  },
  {
    id: "barley",
    slug: "barley",
    name: {
      en: "Barley",
      ar: "الشعير",
      fr: "Orge",
    },
    scientificName: "Hordeum vulgare L.",
    family: "Poaceae",
    category: "cereal",
    description: {
      en: "Hardy cereal cultivated extensively across Algerian steppes and pastoral agro-ecosystems.",
      ar: "محصول حقول متين ومتحمل للجفاف، يُزرع بكثافة في مناطق السهوب والمناطق الرعوية.",
      fr: "Céréale rustique majeure cultivée dans les zones steppiques et agro-pastorales algériennes.",
    },
    varieties: [
      {
        id: "saida",
        name: "Saïda 183",
        code: "ITGC-SAI",
        recommendedZones: ["high_plateaus", "semi_arid_steppes"],
        cycleDays: 140,
        maturity: "early",
        description: {
          en: "Reference Algerian variety renowned for drought endurance and excellent forage/grain yield.",
          ar: "الصنف الجزائري المرجعي المشهور بمقاومته الفائقة للجفاف وإنتاجيته العلفية والحبية.",
          fr: "Variété algérienne de référence célèbre pour sa rusticité face au stress hydrique.",
        },
      },
      {
        id: "tichedrett",
        name: "Tichedrett",
        code: "ITGC-TIC",
        recommendedZones: ["high_plateaus"],
        cycleDays: 145,
        maturity: "early",
        description: {
          en: "Six-row barley adapted to cold plateau soils.",
          ar: "شعير سداسي الصفوف ملائم لتربة الهضاب الباردة.",
          fr: "Orge à 6 rangs adaptée aux sols froids des hauts plateaux.",
        },
      },
    ],
    calendar: [
      {
        phase: "sowing",
        name: { en: "Sowing", ar: "البذر", fr: "Semis" },
        startMonth: 10,
        endMonth: 12,
      },
      {
        phase: "vegetative",
        name: { en: "Vegetative Growth", ar: "النمو الخضري", fr: "Végétation" },
        startMonth: 1,
        endMonth: 3,
      },
      {
        phase: "flowering",
        name: { en: "Flowering", ar: "الإزهار", fr: "Floraison" },
        startMonth: 4,
        endMonth: 4,
      },
      {
        phase: "harvesting",
        name: { en: "Harvest", ar: "الحصاد", fr: "Récolte" },
        startMonth: 5,
        endMonth: 6,
      },
    ],
    primaryWilayas: ["14", "19", "05", "29"],
    requirements: {
      optimalTempMin: 10,
      optimalTempMax: 24,
      waterNeedsMm: 300,
      soilTypes: {
        en: "Sandy loam or calcic steppe soils.",
        ar: "تربة طميية رملية أو كلسية سهبية.",
        fr: "Sols limono-sableux ou calco-magnésiques steppiques.",
      },
      droughtTolerance: "high",
      salinityTolerance: "high",
    },
    afflictionIds: ["septoria-tritici", "yellow-rust"],
    sources: ["itgc", "inraa"],
  },
  {
    id: "olive",
    slug: "olive",
    name: {
      en: "Olive Tree",
      ar: "شجرة الزيتون",
      fr: "Olivier",
    },
    scientificName: "Olea europaea L.",
    family: "Oleaceae",
    category: "fruit_tree",
    description: {
      en: "Heritage tree crop forming the foundation of Algeria's arboriculture and olive oil industry.",
      ar: "شجرة مباركة وتراثية تشكل ركيزة زراعة الأشجار المثمرة وإنتاج زيت الزيتون في الجزائر.",
      fr: "Arbre patrimonial majeur pilier de l'oléiculture et de la production d'huile d'olive en Algérie.",
    },
    varieties: [
      {
        id: "chemlal",
        name: "Chemlal de Kabylie",
        recommendedZones: ["coastal_tell", "high_plateaus"],
        cycleDays: 240,
        maturity: "late",
        description: {
          en: "Most widespread Algerian oil variety; high oil yield and hardy vigor.",
          ar: "أوسع الأصناف الجزائرية انتشاراً، نسبة زيت مرتفعة ومقاومة عالية للظروف البيئية.",
          fr: "Variété à huile la plus répandue en Algérie, excellent rendement en huile.",
        },
      },
      {
        id: "sigoise",
        name: "Sigoise (Picholine marocaine)",
        recommendedZones: ["semi_arid_steppes", "coastal_tell"],
        cycleDays: 220,
        maturity: "medium",
        description: {
          en: "Dual-purpose olive (table & oil), famous in Mascara and Sig plains.",
          ar: "صنف ثنائي الغرض (مائدة وعصر)، تشتهر به سهول سيق ومعسكر.",
          fr: "Variété mixte (table et huile), reine de la plaine du Sig et Mascara.",
        },
      },
    ],
    calendar: [
      {
        phase: "vegetative",
        name: { en: "Budburst & Pruning", ar: "استيقاظ البراعم والتقليم", fr: "Débourrement & Taille" },
        startMonth: 2,
        endMonth: 3,
      },
      {
        phase: "flowering",
        name: { en: "Flowering", ar: "الإزهار", fr: "Floraison" },
        startMonth: 4,
        endMonth: 5,
      },
      {
        phase: "maturation",
        name: { en: "Fruit Development", ar: "نمو الثمار والتحول اللوني", fr: "Véraison" },
        startMonth: 6,
        endMonth: 9,
      },
      {
        phase: "harvesting",
        name: { en: "Olive Harvest", ar: "جني الزيتون", fr: "Récolte des olives" },
        startMonth: 10,
        endMonth: 1,
      },
    ],
    primaryWilayas: ["29", "09", "02", "31"],
    requirements: {
      optimalTempMin: 15,
      optimalTempMax: 32,
      waterNeedsMm: 400,
      soilTypes: {
        en: "Deep calcareous stony or loamy soils, intolerant to waterlogging.",
        ar: "تربة كلسية حصوية أو طميية جيدة الصرف، حساسة جداً للرطوبة الزائدة.",
        fr: "Sols calcaires caillouteux bien drainés, redoute l'asphyxie racinaire.",
      },
      droughtTolerance: "high",
      salinityTolerance: "moderate",
    },
    afflictionIds: ["olive-fruit-fly"],
    sources: ["inraa", "madr", "cnma"],
  },
  {
    id: "date-palm",
    slug: "date-palm",
    name: {
      en: "Date Palm",
      ar: "نخيل التمر",
      fr: "Palmier Dattier",
    },
    scientificName: "Phoenix dactylifera L.",
    family: "Arecaceae",
    category: "fruit_tree",
    description: {
      en: "Cornerstone of the Saharan oasis ecosystem and premium Algerian export crop.",
      ar: "عماد الواحات الصحراوية ومصدر التمور الجزائرية الفاخرة الموجهة للتصدير والاستهلاك.",
      fr: "Pilier de l'écosystème oasien saharien et joyau de l'exportation agroalimentaire algérienne.",
    },
    varieties: [
      {
        id: "deglet-nour",
        name: "Deglet Nour",
        code: "ITDAS-DEG",
        recommendedZones: ["saharan_oases"],
        cycleDays: 240,
        maturity: "late",
        description: {
          en: "The 'Queen of Dates', translucent amber fruit world-renowned from Biskra (Tolga) and El Oued.",
          ar: "سيدة التمور 'دقلة نور' الشفافة والعسلية، مشهورة عالمياً من بسكرة (طولقة) ووادي سوف.",
          fr: "La reine des dattes, fruit translucide couleur miel mondialement réputé de Biskra (Tolga) et El Oued.",
        },
      },
      {
        id: "ghars",
        name: "Ghars",
        code: "ITDAS-GHA",
        recommendedZones: ["saharan_oases"],
        cycleDays: 210,
        maturity: "early",
        description: {
          en: "Soft, sweet date consumed early, highly resistant to oasis heat.",
          ar: "تمر طري غني بالسكر، مبكر النضج وذو قيمة غذائية عالية ومقاوم للحرارة.",
          fr: "Datte molle très précoce et énergétique, rustique en milieu aride.",
        },
      },
    ],
    calendar: [
      {
        phase: "flowering",
        name: { en: "Pollination (Dokkar)", ar: "التلقيح اليدوي (التذكير)", fr: "Pollinisation manuelle" },
        startMonth: 3,
        endMonth: 4,
      },
      {
        phase: "vegetative",
        name: { en: "Bunch Thinning & Bagging", ar: "تعديل وتكميم العراجين", fr: "Ciselage & Ensachage" },
        startMonth: 5,
        endMonth: 7,
      },
      {
        phase: "maturation",
        name: { en: "Ripening (Khalal & Rutab)", ar: "نضج البسر والرطب", fr: "Maturation (Bser/Rutab)" },
        startMonth: 8,
        endMonth: 9,
      },
      {
        phase: "harvesting",
        name: { en: "Date Harvest (Glaa)", ar: "موسم جني التمور (القلاع)", fr: "Récolte des dattes" },
        startMonth: 10,
        endMonth: 12,
      },
    ],
    primaryWilayas: ["07", "39"],
    requirements: {
      optimalTempMin: 25,
      optimalTempMax: 45,
      waterNeedsMm: 1200,
      soilTypes: {
        en: "Sandy or light loamy oasis soils with good groundwater drainage.",
        ar: "تربة رملية أو طميية خفيفة جيدة الصرف للمياه الجوفية.",
        fr: "Sols sableux ou limoneux filtrants des oasis.",
      },
      droughtTolerance: "high",
      salinityTolerance: "high",
    },
    afflictionIds: ["red-palm-weevil"],
    sources: ["itdas", "inraa", "madr"],
  },
  {
    id: "potato",
    slug: "potato",
    name: {
      en: "Potato",
      ar: "البطاطا",
      fr: "Pomme de Terre",
    },
    scientificName: "Solanum tuberosum L.",
    family: "Solanaceae",
    category: "vegetable",
    description: {
      en: "Essential vegetable crop with multiple Algerian seasonal cycles (early, season, late, and saharan rear-season).",
      ar: "محصول خضروات استراتيجي يُزرع في عدة عروات موسمية ومبكرة وما بعد موسمية في واد سوف ومعسكر ومستغانم.",
      fr: "Culture maraîchère stratégique à cycles multiples (primeur, saison et arrière-saison saharienne à El Oued).",
    },
    varieties: [
      {
        id: "spunta",
        name: "Spunta",
        recommendedZones: ["saharan_oases", "coastal_tell", "high_plateaus"],
        cycleDays: 110,
        maturity: "early",
        description: {
          en: "Dominant yellow-flesh variety in Algeria, very popular with growers and consumers.",
          ar: "الصنف الأصفر المهيمن في السوق الجزائرية، عالي المردودية وسريع النمو.",
          fr: "Variété dominante à chair jaune en Algérie, très productive et appréciée.",
        },
      },
    ],
    calendar: [
      {
        phase: "sowing",
        name: { en: "Planting (Arrière-saison)", ar: "غرس درنات البذور", fr: "Plantation des tubercules" },
        startMonth: 8,
        endMonth: 9,
      },
      {
        phase: "vegetative",
        name: { en: "Ridging & Tuberization", ar: "التكتيل وتكوين الدرنات", fr: "Buttage & Tubérisation" },
        startMonth: 10,
        endMonth: 11,
      },
      {
        phase: "harvesting",
        name: { en: "Tuber Harvest", ar: "قلع البطاطا", fr: "Récolte des tubercules" },
        startMonth: 12,
        endMonth: 1,
      },
    ],
    primaryWilayas: ["39", "27", "19", "29"],
    requirements: {
      optimalTempMin: 15,
      optimalTempMax: 24,
      waterNeedsMm: 500,
      soilTypes: {
        en: "Loose sandy-loam, free of stones, slightly acidic to neutral.",
        ar: "تربة رملية طميية مفككة خالية من الحجارة جيدة التهوية.",
        fr: "Sols légers sablo-limoneux meubles et aérés.",
      },
      droughtTolerance: "low",
      salinityTolerance: "moderate",
    },
    afflictionIds: ["late-blight", "tuta-absoluta"],
    sources: ["inraa", "madr", "cnma"],
  },
  {
    id: "tomato",
    slug: "tomato",
    name: {
      en: "Tomato",
      ar: "الطماطم",
      fr: "Tomate",
    },
    scientificName: "Solanum lycopersicum L.",
    family: "Solanaceae",
    category: "vegetable",
    description: {
      en: "Leading greenhouse and open-field vegetable, including industrial processing in Guelma and early dessert production in Biskra.",
      ar: "محصول خضري رائد يُزرع حقلياً في قالمة للصناعة التحويلية وتحت البيوت المحمية في بسكرة للاستهلاك الطازج.",
      fr: "Culture maraîchère leader sous serre à Biskra et en plein champ industriel à Guelma.",
    },
    varieties: [
      {
        id: "rio-grande",
        name: "Rio Grande",
        recommendedZones: ["coastal_tell", "high_plateaus"],
        cycleDays: 120,
        maturity: "medium",
        description: {
          en: "Blocky firm tomato for processing and market.",
          ar: "صنف بيضوي متماسك ملائم للحقل المفتوح والصناعات الغذائية.",
          fr: "Tomate déterminée ferme idéale pour le plein champ et la transformation.",
        },
      },
    ],
    calendar: [
      {
        phase: "sowing",
        name: { en: "Nursery / Transplanting", ar: "التشتيل والغرس في الحقل", fr: "Pépinière & Repiquage" },
        startMonth: 1,
        endMonth: 3,
      },
      {
        phase: "vegetative",
        name: { en: "Vegetative & Trellising", ar: "التربية والتقليم والربط", fr: "Palissage & Végétation" },
        startMonth: 4,
        endMonth: 5,
      },
      {
        phase: "harvesting",
        name: { en: "Harvest", ar: "جني الطماطم", fr: "Récolte" },
        startMonth: 6,
        endMonth: 8,
      },
    ],
    primaryWilayas: ["07", "24", "27"],
    requirements: {
      optimalTempMin: 18,
      optimalTempMax: 30,
      waterNeedsMm: 600,
      soilTypes: {
        en: "Fertile loamy soils rich in organic matter with neutral pH.",
        ar: "تربة طميية خصبة غنية بالدبال ومعتدلة الحموضة.",
        fr: "Sols limoneux fertiles et riches en humus.",
      },
      droughtTolerance: "low",
      salinityTolerance: "moderate",
    },
    afflictionIds: ["tuta-absoluta", "late-blight"],
    sources: ["inraa", "madr"],
  },
  {
    id: "citrus",
    slug: "citrus",
    name: {
      en: "Citrus Fruits",
      ar: "الحمضيات",
      fr: "Agrumes",
    },
    scientificName: "Citrus sinensis / Citrus clementina",
    family: "Rutaceae",
    category: "fruit_tree",
    description: {
      en: "High-value orchard crops centered in the Mitidja plain (Blida), coastal Chlef, and Mostaganem.",
      ar: "بساتين مثمرة عالية القيمة تتركز في سهل متيجة (البليدة)، حوض الشلف، وسواحل مستغانم.",
      fr: "Vergers à haute valeur ajoutée centrés dans la Mitidja (Blida), le Chéliff et Mostaganem.",
    },
    varieties: [
      {
        id: "thomson-navel",
        name: "Thomson Navel",
        recommendedZones: ["coastal_tell"],
        cycleDays: 210,
        maturity: "medium",
        description: {
          en: "Juicy dessert orange widely cultivated in the Mitidja plain.",
          ar: "برتقال مائدة شهير بحلاوته وعصارته يزرع بكثافة في متيجة.",
          fr: "Orange de table renommée de la plaine de la Mitidja.",
        },
      },
      {
        id: "clementine-misserghin",
        name: "Clémentine de Misserghin",
        recommendedZones: ["coastal_tell"],
        cycleDays: 180,
        maturity: "early",
        description: {
          en: "Historical birthplace of the Clementine (Oran/Misserghin), sweet and seedless.",
          ar: "الموطن التاريخي الأول للكليمونتين (مسرغين، وهران)، حلو وخالٍ من البذور.",
          fr: "Berceau historique mondial de la clémentine (Misserghin, Oran), sans pépins.",
        },
      },
    ],
    calendar: [
      {
        phase: "flowering",
        name: { en: "Bloom & Fruit Set", ar: "الإزهار وعقد الثمار", fr: "Floraison & Nouaison" },
        startMonth: 3,
        endMonth: 5,
      },
      {
        phase: "maturation",
        name: { en: "Fruit Swelling & Degreening", ar: "تضخم الثمار وتلون القشرة", fr: "Grossissement & Coloration" },
        startMonth: 6,
        endMonth: 10,
      },
      {
        phase: "harvesting",
        name: { en: "Harvest", ar: "جني البرتقال واليوسفي", fr: "Récolte des agrumes" },
        startMonth: 11,
        endMonth: 3,
      },
    ],
    primaryWilayas: ["09", "02", "27", "16"],
    requirements: {
      optimalTempMin: 18,
      optimalTempMax: 30,
      waterNeedsMm: 800,
      soilTypes: {
        en: "Deep sandy-clay alluvium, free of active limestone.",
        ar: "تربة غرينية عميقة رملية طينية خالية من الكلس الفعال.",
        fr: "Sols alluvionnaires profonds, légers et sans calcaire actif.",
      },
      droughtTolerance: "low",
      salinityTolerance: "low",
    },
    afflictionIds: [],
    sources: ["inraa", "madr"],
  },
];
